
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyqqyeixjgbwdjtmqbzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5cXF5ZWl4amdid2RqdG1xYnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTc0ODQsImV4cCI6MjA1ODEzMzQ4NH0.vQW1nI8VnFQ-rsRVJTr-mvI4s0VDkKLH0TLrofLXK8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
